### ISSUE TITLE
Push Notification?

### ISSUE THREAD

**Issue by MTRNord** [don/node-eddystone-beacon#43]
I am not aware of any specifications in Eddystone (really new to it) but is it possible to do advertise with an push notfification custom texts like "Hi there at the sportclub near you is event why don't you want to have a look it"?

**Comment by jacobrosenthal** [comment]
Maybe not super appropriate for this repo as this is an unaffiliated javascript implementation of the eddystone spec that (generally speaking) runs in node where there is no concept of push notifications.... But, to answer your question, none of the operating systems will do that by default  because nobody wants eddystone/beacons to turn into spam. On ios and android you can make a native app which has access to notifications apis and the eddystone/beacon apis and your app can trigger a notification when it sees a beacon/eddystone.

**Comment by MTRNord** [comment]
Ah ok :) thanks for awnser :+1:

**Comment by jacobrosenthal** [comment]
Np :)

If you wanna watch eddystone chit chat and see the specs, check out googles repos
https://github.com/google/eddystone
https://github.com/google/physical-web

**Comment by MTRNord** [comment]
If I am right doing the URL thing would be the same if I add an description and title to it like in the Docs and it would look like an Push Notification? Of course it isn't

**Comment by MTRNord** [comment]
(I refer to the line "Do use the Physical Web name and/or logo to indicate that a nearby device is broadcasting Eddystone-URL advertisement packets, e.g. on your visual advertisements or in your coffee shop" in https://github.com/google/physical-web/blob/master/documentation/branding_guidelines.md

**Comment by jacobrosenthal** [comment]
So you can advertise a url. On android what happens (or theyre rolling out) is that there will be a notification if the user looks for it on their notifications screen, but theres no buzz or beep, etc related to it.

**Comment by MTRNord** [comment]
Ok than I have an Idea to do the thing I want :) but thanks for help
